name: Zip repository and create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  zip-n-release:
    name: Zip and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure all history is fetched

      - name: Zip Folder
        run: |
          zip -r release.zip . -x ".git/*" ".github/*"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
